Mobile Contact Form Pull Request
MussieTeka/Mussie-s-Portfolio pull request #4
Opened 2023-02-21 13:53 UTC by MussieTeka

I have added an updated index.html and style.css to the project to create the contact form part of the website.

2023-02-21 15:12 UTC, Owusu-Desmond requested changes
Hi @MussieTeka and @Otegaa , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 15:12 UTC, Owusu-Desmond commented on style.css
> +
- [ ] Please make the  `Get in touch`  button follow the button styling: Active, Hover, and Pressed (see design)
  
  ### YOUR DESIGN
  
  ![image](https://user-images.githubusercontent.com/92303891/220382366-e893ea66-ac98-4b61-b953-216bf73eb370.png)
  
  ### Figma Design
  ![Screenshot from 2022-12-03 19-12-27](https://user-images.githubusercontent.com/92303891/205457943-227f0990-7771-43ac-9c9c-dc7f6cdd5c46.png)

2023-02-22 09:11 UTC, MussieTeka commented on style.css
> +
Thank you for your feedback. I have implemented the suggested changes and added Active, Hover, Pressed, and Disabled button styling to the style.css file as per your remark.

2023-02-22 09:22 UTC, amejid approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Good UI design :heavy_check_mark: 
- Button interactions working :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 09:27 UTC, merged